schema_version: 1

context:
  name: lgatr
  version: "1.4.2"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/lgatr-${{ version }}.tar.gz
  sha256: 518e82c477ab3f03be2549281b9922c25e21dedc553a063edd3acf70a0c438c2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68
    - wheel >=0.42
    - pip
  run:
    - python >=${{ python_min }}
    - pytorch >=2.0
    - numpy
    - einops
    - opt_einsum

tests:
  - python:
      imports:
        - lgatr
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Lorentz-Equivariant Geometric Algebra Transformer for High-Energy Physics
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/heidelberg-hepml/lgatr
  repository: https://github.com/heidelberg-hepml/lgatr
  documentation: https://heidelberg-hepml.github.io/lgatr/

extra:
  recipe-maintainers:
    - spinjo
